### ISSUE TITLE
Updating VinPrefixes.txt

### ISSUE THREAD

**Issue by overstable** [yanigisawa/VinGenerator#1]
How can one get the data for updating VinPrefixes.txt ? 
Is there a source for getting new ones?

**Comment by yanigisawa** [comment]
[NADA](http://www.nada.com/b2b/homepage.aspx) has a paid service a business can subscribe to for the latest valuations and VIN listings. If you call them, they may be able to provide you an updated list of VIN WMIs and Make / Model / Year prefixes for a reduced cost for education or project-specific use cases.

Some other resources that may be helpful:
[NHTSA VIN Decoder Service](https://vpic.nhtsa.dot.gov/api/)
[DMV Vin Decoder](http://www.dmv.org/vehicle-history/vin-decoder.php)
[List Of WMIs](https://en.wikibooks.org/wiki/Vehicle_Identification_Numbers_(VIN_codes)/World_Manufacturer_Identifier_(WMI)#List_of_all_WMIs)
[My Random VIN Generator](http://jamesralexander.com/util/vin) - Includes a QR Code that you can scan into another app for testing their VIN Barcode scanner
[Other Random VIN Generator](http://randomvin.com/)
[EBay Motors](https://www.ebay.com/motors) - Drill down to find a specific car, then scroll down the car's listing page to view the real VIN for a real car. (i.e. not a randomly generated VIN)
