### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by wallymathieu** [yanigisawa/VinGenerator#2]
Hi what's the license of this library? Best regards

**Comment by yanigisawa** [comment]
Added MIT license. 

I'm curious, how did you find this code? It seems to have gotten more attention (i.e. 2 or  three stars) recently, and I don't know why that would be. (after 7 years of being idle)

**Comment by wallymathieu** [comment]
Well, we are talking about porting it to .net (c#). Since the code is relatively simple and straight forward it's a great choice.
